version: 2

jobs:
  build:
    docker:
      - image: alpine
    working_directory: /mnt/ramdisk

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo ''export VER=$(echo $(cat ./package.json | grep version | head -1 | awk -F: ''''{ print $2 }'''' | sed ''''s/[",]//g'''' | tr -d ''''[[:space:]]''''))'' >> $BASH_ENV
            docker build --build-arg APP_VERSION=$VER -t docker.mitrasinovic.co.uk/exoscale-circleci-nodejs:$VER .
            echo "$DOCKER_PASS" | docker login docker.mitrasinovic.co.uk -u $DOCKER_USER --password-stdin
            docker push docker.mitrasinovic.co.uk/exoscale-circleci-nodejs:$VER

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: Quesmed
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
