version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build --build-arg APP_VERSION=$CIRCLE_TAG -t docker.mitrasinovic.co.uk/exoscale-circleci-nodejs:$CIRCLE_TAG .
            echo "$DOCKER_PASS" | docker login docker.mitrasinovic.co.uk -u $DOCKER_USER --password-stdin
            docker push docker.mitrasinovic.co.uk/exoscale-circleci-nodejs:$CIRCLE_TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: Quesmed
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
